### ISSUE TITLE
Accounts statistics doesn't update

### ISSUE THREAD

**Issue by ndoody** [modoboa/modoboa#2644]
Hi, I have recently upgraded from 1.17.0 to 2.0.0 and then to 2.0.2.

After upgrading to 2.0.0 everything loaded up but I noticed the following :-

- The new v2 interface has hard coding to /new-admin/ but I am on a differentpath (/tools/managemail/) so nothing worked, I had to replace multiple entries inside the various files so that it pointed correctly and then it worked.  Suggest you remove the static entries, or make some way to specify a different path.  SAme in 2.0.2 by the looks of things.
- The statistics page on the legacy interface is now blank, it doesn't show me any statistics.  I can see statistics per domain inside the new admin page.

After upgrading to 2.0.2, catastrophic failures :-

- ImportError: cannot import name python_2_unicode_compatible - this error pops up from multiple files / extensions.  I tried pip upgrade to some of these extensions and they have the same issue still.  I found a solution and added it to several files, instead use import python_2_unicode_compatible from six as a workaround, since latest django has this removed from what I had read.

I have solved most of the issues myself with workaround, but the statistics page on the legacy admin is still blank - any fix for that or something I can try?

**Comment by ndoody** [comment]
> Please check #2613: try to reboot :)

Thanks, statistics started appearing for mail traffic - i didnt do anything, it just started working.

Doesn't appear for accouts, but no error it would seem.

**Comment by PatTheMav** [comment]
It should be noted that there's also an open bug with vue-apexcharts that was merged already, but will be part of a 2.0.4 release in the future I guess:

https://github.com/modoboa/modoboa/pull/2661
