### ISSUE TITLE
Policy daemon won't start

### ISSUE THREAD

**Issue by erik-dekker** [modoboa/modoboa#2561]
# Impacted versions

* OS Type: Ubuntu 
* OS Version: 22
* Database Type: PostgreSQ
* Database version: 14
* Modoboa: 2.0.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

* Install Modoboa on Ubuntu 22 with installer
* Monitor supervisor with`journalctl -u supervisor -f`
* Notice it keeps restarting, because the python script has errors.

# Current behavior

Running policy_daemon manually shows the error. It seems that the loop parameter was removed from asyncio:
https://bugs.python.org/issue46796

```
(env) modoboa@mail:~/instance$ python -V
Python 3.10.4
```
```
(env) modoboa@mail:~/instance$ python manage.py policy_daemon
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 22, in <module>
    main()
  File "/srv/modoboa/instance/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.10/site-packages/modoboa/policyd/management/commands/policy_daemon.py", line 39, in handle
    server = loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/asyncio/streams.py", line 84, in start_server
    return await loop.create_server(factory, host, port, **kwds)
TypeError: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'
```

# Expected behavior

The daemon should do daemon things instead of crashing.

**Comment by tonioo** [comment]
Looks like a Python 3.10 compatibility issue. Modoboa has been tested with this version yet so the support is not official.

**Comment by gsloop** [comment]
@Spitfireap 
Did you solve this, or have a decent work-around?

**Comment by gsloop** [comment]
So, I have NO idea if @Spitfireap's suggestion is a good idea or not, but I've provisionally tested it, and it does allow supervisord to start. that fixes several problems
!) The inability to send/receive mail because policyd/supervisord isn't started.
2) A weird calendar bug, where you can't add calendar entries or edit the name/color of a calendar. (See: https://github.com/modoboa/modoboa/issues/2571)

**Comment by Spitfireap** [comment]
Nice to see it fixed, as for calendar issue, it's really weird. 

You said that it wasn't working on Ubuntu 20.04 but 20.04 doesn't have python 3.10 😅.

**Comment by erik-dekker** [comment]
Removing the `loop=loop` parameter from line 37 does indeed fix this issue. However, I'm not sure if this breaks something in lower Python versions?

**Comment by gsloop** [comment]
A quick two liner that "fixes" this on Ubuntu 22.04. (Fresh install of 22.04 and stock Modoboa install using the python install script.)

cp /srv/modoboa/env/lib/python3.10/site-packages/modoboa/policyd/management/commands/policy_daemon.py /srv/modoboa/env/lib/python3.10/site-packages/modoboa/policyd/management/commands/policy_daemon.py.bak

sed -i 's/, loop=loop/ /' /srv/modoboa/env/lib/python3.10/site-packages/modoboa/policyd/management/commands/policy_daemon.py

This certainly appears to work on Ubuntu 22.04, and SHOULD NOT be considered a fix on any other distro or version! I am unable to find any bad impacts from this fix. If someone finds some, it would be helpful to post an update here!
