### ISSUE TITLE
Fatal error after updating to 1.8.2

### ISSUE THREAD

**Issue by mundschenk-at** [modoboa/modoboa#1202]
# Impacted versions

* Modoboa: 1.8.2
* installer used: No
* Webserver: Nginx

# Steps to reproduce
* Update Modoboa 1.8.2 to 1.8.2
* Try to run `python manage.py migrate`

# Current behavior
```
Traceback (most recent call last):
  File "/usr/local/libexec/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/libexec/modoboa/instance/instance/urls.py", line 4, in <module>
    url(r'', include('modoboa.urls')),
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/modoboa/urls.py", line 57, in <module>
    url("^api/v1/", include("modoboa.urls_api", namespace="api")),
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/modoboa/urls_api.py", line 14, in <module>
    urlpatterns += exts_pool.get_urls(category="api")
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/modoboa/core/extensions.py", line 118, in get_urls
    url(root, include(pattern.format(ext_name), **options))
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/modoboa_contacts/urls_api.py", line 5, in <module>
    from . import viewsets
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/modoboa_contacts/viewsets.py", line 3, in <module>
    import django_filters.rest_framework
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django_filters/rest_framework/__init__.py", line 3, in <module>
    from .backends import DjangoFilterBackend
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/django_filters/rest_framework/backends.py", line 7, in <module>
    from rest_framework.filters import BaseFilterBackend
  File "/usr/local/libexec/modoboa/env/lib/python2.7/site-packages/rest_framework/filters.py", line 54, in <module>
    DFBase = django_filters.rest_framework.DjangoFilterBackend
AttributeError: 'NoneType' object has no attribute 'DjangoFilterBackend'
```
# Expected behavior
A clean run of the migrate script.

**Comment by mundschenk-at** [comment]
Disabling `modoboa-contacts` fixed the problem for the while being. Apparently some change in 1.8.2 is not compatible with it.

**Comment by TacoScheltema** [comment]
I just had the same error when upgrading from 1.8.1 to 1.8.2
After restarting uwsgi I get a 501 error in my browser.

I reverted to 1.8.1 which made it work again.

Steps to revert:
```
su - modoboa
source env/bin/activate
pip install modoboa==1.8.1
cd instance/
python manage.py migrate
python manage.py collectstatic
```
restart uwsgi after these steps.

**Comment by tonioo** [comment]
Guys, please update ``django-filters`` package to latest version, I'll push a new contacts release soon.

**Comment by mundschenk-at** [comment]
Updating `django-filter` (no `s`!) to 1.0.4 indeed fixed the issue for me.

**Comment by TacoScheltema** [comment]
that worked, instructions for all us non-developers out there:

```
su - modoboa
source env/bin/activate
pip install django-filter==1.0.4
pip install modoboa==1.8.2
cd instance/
python manage.py migrate
python manage.py collectstatic
```
and restart uwsgi

**Comment by tonioo** [comment]
I've just released a 0.4.0 version of the contacts plugin which fixes this issue.
