### ISSUE TITLE
cleanlogs cron job error

### ISSUE THREAD

**Issue by yannfill** [modoboa/modoboa#1066]
* Modoboa: 1.7.0
* installer used: No
* Webserver: Apache

Since update to 1.7.0 the cron job `$PYTHON $INSTANCE/manage.py cleanlogs` fails with this error:
```
/usr/local/lib/python2.7/dist-packages/cffi/model.py:532: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
Traceback (most recent call last):
  File "/opt/ModoboaWeb/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/modoboa/core/management/commands/cleanlogs.py", line 11, in <module>
    from ... import parameters
ImportError: cannot import name parameters
```

**Comment by yannfill** [comment]
Duplicate of #1065
